[package]
name = "combinators"
version = "0.1.0"
authors = ["DMorgan <daniel.bechaz@gmail.com>"]
edition = "2018"
description = "A library of combinator functions with named types"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
